# Owner
owner: williambargent-org # Your GitHub username
repo: williambargent-org.github.com # Your Github repository name

# Sites
sites:
  - name: Website
    url: https://williambargent.co.uk
    icon: https://assets.williambargent.co.uk/favicon/favicon.ico
    maxResponseTime: 3000
  - name: WeatherMX
    url: https://weathermx.williambargent.co.uk
    icon: https://weathermx.williambargent.co.uk/assets/img/logo/favicon.ico
    maxResponseTime: 3000
  - name: Identity
    url: https://identity.williambargent.co.uk
    icon: https://assets.williambargent.co.uk/favicon/favicon.ico
    maxResponseTime: 3000
  - name: Gallery
    url: https://gallery.williambargent.co.uk
    icon: https://assets.williambargent.co.uk/favicon/favicon.ico
    maxResponseTime: 3000

# Options
status-website:
  cname: status.williambargent.co.uk
  baseUrl: /
  name: Status - William Bargent
  logoUrl: https://assets.williambargent.co.uk/images/wb/logos/full.min.png
  introTitle: "Service Status"
  introMessage: "This site will automatically update with outages."
  navbar:
    - title: Home
      href: https://williambargent.co.uk
    - title: WeatherMX
      href: https://weathermx.williambargent.co.uk
  links:
    - rel: stylesheet
      href: https://raw.githubusercontent.com/williambargent-org/Global-Asset-Repository/main/status/css/overrides.css
  skipDescriptionUpdate: true
  skipTopicsUpdate: true
  skipHomepageUpdate: true
  commitMessages:
    commitAuthorName: "Upptime Bot"
    commitAuthorEmail: "upptime@williambargent.co.uk"
